// ==========================================
// 1. REGISTRY ITEMS ARRAY
// ==========================================
export const registryItems = [
  {
    id: 1,
    title: "Morphy Richards Blender",
    price: 250,
    image: "https://images.unsplash.com/photo-1578643463396-0997cb5328c1?auto=format&fit=crop&w=500&q=80",
    claimed: false
  },
  {
    id: 2,
    title: "Nespresso Vertuo Coffee Machine",
    price: 850,
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=500&q=80",
    claimed: false
  },
  {
    id: 3,
    title: "Dyson V15 Detect Vacuum",
    price: 2800,
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=500&q=80",
    claimed: false
  },
  {
    id: 4,
    title: "KitchenAid Stand Mixer",
    price: 2100,
    image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=500&q=80",
    claimed: false
  },
  {
    id: 5,
    title: "Staub Cast Iron Cocotte",
    price: 950,
    image: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=500&q=80",
    claimed: false
  },
  {
    id: 6,
    title: "Riedel Wine Glass Set (Set of 6)",
    price: 450,
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=500&q=80",
    claimed: false
  },
  {
    id: 7,
    title: "Samsonite Luggage Set",
    price: 1500,
    image: "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=500&q=80",
    claimed: false
  },
  {
    id: 8,
    title: "Sonos Era 100 Smart Speaker",
    price: 990,
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=500&q=80",
    claimed: false
  }
];

// ==========================================
// 2. BACKEND PERSISTENCE CONFIGURATION
// ==========================================
// To enable real-time synchronization, configure your preferred backend provider below.
// If provider is set to 'local', or configuration keys are missing, the registry falls 
// back to local storage syncing, allowing offline/demo testing out of the box.
const DATABASE_CONFIG = {
  provider: 'local', // Options: 'local', 'supabase', 'firebase'
  
  // Supabase Configuration
  // ----------------------------------------
  // SQL Schema for your Supabase database:
  // create table registry_claims (
  //   id bigint generated by default as identity primary key,
  //   item_id integer unique not null,
  //   claimed boolean default false,
  //   claimer_name text,
  //   claimer_email text,
  //   created_at timestamp with time zone default timezone('utc'::text, now()) not null
  // );
  // Alter table to enable Realtime:
  // alter publish to supabase_realtime add table registry_claims;
  supabase: {
    url: '', // Add your Supabase Project URL
    anonKey: '', // Add your Supabase Anon API Key
    table: 'registry_claims'
  },
  
  // Firebase Configuration
  // ----------------------------------------
  // Setup a Firestore Database with a 'registry_claims' collection.
  // Documents in the collection will use the item ID string as the document name.
  firebase: {
    apiKey: "",
    authDomain: "",
    projectId: "",
    storageBucket: "",
    messagingSenderId: "",
    appId: ""
  }
};

// ==========================================
// 3. DATABASE CLIENT STATE & SYNC ENGINE
// ==========================================
let dbProvider = 'local';
let supabaseClient = null;
let firestoreDb = null;

// Initialize clients based on config
function initDatabase() {
  const statusEl = document.getElementById('sync-status');
  const statusTextEl = document.getElementById('sync-status-text');

  if (DATABASE_CONFIG.provider === 'supabase' && DATABASE_CONFIG.supabase.url && DATABASE_CONFIG.supabase.anonKey) {
    try {
      supabaseClient = supabase.createClient(DATABASE_CONFIG.supabase.url, DATABASE_CONFIG.supabase.anonKey);
      dbProvider = 'supabase';
      console.log("Supabase client initialized successfully.");
      
      // Update badge
      statusEl.classList.remove('hidden');
      statusEl.classList.add('flex');
      statusEl.className = statusEl.className.replace(/bg-\w+-\d+/g, 'bg-emerald-50').replace(/text-\w+-\d+/g, 'text-emerald-800').replace(/border-\w+-\d+/g, 'border-emerald-100');
      statusTextEl.innerText = "Live Realtime Sync (Supabase)";
      
      setupSupabaseSync();
      return;
    } catch (e) {
      console.error("Failed to initialize Supabase, fallback to localStorage:", e);
    }
  } else if (DATABASE_CONFIG.provider === 'firebase' && DATABASE_CONFIG.firebase.projectId) {
    try {
      firebase.initializeApp(DATABASE_CONFIG.firebase);
      firestoreDb = firebase.firestore();
      dbProvider = 'firebase';
      console.log("Firebase Firestore initialized successfully.");

      // Update badge
      statusEl.classList.remove('hidden');
      statusEl.classList.add('flex');
      statusEl.className = statusEl.className.replace(/bg-\w+-\d+/g, 'bg-emerald-50').replace(/text-\w+-\d+/g, 'text-emerald-800').replace(/border-\w+-\d+/g, 'border-emerald-100');
      statusTextEl.innerText = "Live Realtime Sync (Firebase)";

      setupFirebaseSync();
      return;
    } catch (e) {
      console.error("Failed to initialize Firebase, fallback to localStorage:", e);
    }
  }

  // Fallback / Default Local Sync
  dbProvider = 'local';
  console.log("Using Local Storage Sync.");
  statusEl.classList.remove('hidden');
  statusEl.classList.add('flex');
  statusEl.className = statusEl.className.replace(/bg-\w+-\d+/g, 'bg-plum/5').replace(/text-\w+-\d+/g, 'text-plum/80').replace(/border-\w+-\d+/g, 'border-plum/20');
  statusTextEl.innerText = "Demo Mode (Local Storage)";
  setupLocalSync();
}

// -- Supabase Realtime synchronization
function setupSupabaseSync() {
  if (!supabaseClient) return;

  // 1. Initial Load
  supabaseClient
    .from(DATABASE_CONFIG.supabase.table)
    .select('item_id, claimed')
    .then(({ data, error }) => {
      if (error) {
        console.error("Error loading registry items from Supabase:", error);
        return;
      }
      if (data) {
        data.forEach(row => {
          const item = registryItems.find(i => i.id === row.item_id);
          if (item) {
            item.claimed = row.claimed;
          }
        });
        renderGrid();
      }
    });

  // 2. Realtime Channel Subscription
  supabaseClient
    .channel('public:registry_claims')
    .on('postgres_changes', { event: '*', schema: 'public', table: DATABASE_CONFIG.supabase.table }, payload => {
      const updatedRow = payload.new;
      if (updatedRow && updatedRow.item_id !== undefined) {
        const item = registryItems.find(i => i.id === updatedRow.item_id);
        if (item) {
          item.claimed = updatedRow.claimed;
          renderGrid();
        }
      }
    })
    .subscribe();
}

// -- Firebase Realtime synchronization
function setupFirebaseSync() {
  if (!firestoreDb) return;

  firestoreDb.collection('registry_claims')
    .onSnapshot(snapshot => {
      snapshot.docChanges().forEach(change => {
        const docData = change.doc.data();
        const itemId = parseInt(change.doc.id, 10);
        const item = registryItems.find(i => i.id === itemId);
        if (item) {
          item.claimed = docData.claimed;
        }
      });
      renderGrid();
    }, error => {
      console.error("Error subscribing to Firebase:", error);
    });
}

// -- Local Storage Sync
function setupLocalSync() {
  loadLocalClaims();

  // Handle storage updates in separate browser tabs
  window.addEventListener('storage', (event) => {
    if (event.key === 'registry_claims') {
      loadLocalClaims();
    }
  });
}

function loadLocalClaims() {
  const savedClaims = localStorage.getItem('registry_claims');
  if (savedClaims) {
    try {
      const claims = JSON.parse(savedClaims);
      // Reset items in list to false first
      registryItems.forEach(i => i.claimed = false);
      // Set true for claimed items
      Object.keys(claims).forEach(idStr => {
        const itemId = parseInt(idStr, 10);
        const item = registryItems.find(i => i.id === itemId);
        if (item && claims[idStr].claimed) {
          item.claimed = true;
        }
      });
    } catch (e) {
      console.error("Error parsing local storage claims:", e);
    }
  }
  renderGrid();
}

// ==========================================
// 4. UI RENDERING AND STATE PRESENTATION
// ==========================================
function renderGrid() {
  const grid = document.getElementById('product-grid');
  if (!grid) return;
  
  grid.innerHTML = '';

  registryItems.forEach((item, index) => {
    const isClaimed = item.claimed;
    
    // Grid Card container
    const card = document.createElement('div');
    card.className = `registry-card bg-white rounded-2xl overflow-hidden border border-paleBlush/30 flex flex-col h-full fade-in-item ${isClaimed ? 'claimed-card shadow-sm' : 'shadow-sm'}`;
    card.style.animationDelay = `${index * 40}ms`;
    
    // Formatting currency in NIS (₪)
    const formattedPrice = new Intl.NumberFormat('he-IL', { 
      style: 'currency', 
      currency: 'ILS', 
      maximumFractionDigits: 0 
    }).format(item.price);
    
    let buttonHtml = '';
    if (isClaimed) {
      buttonHtml = `
        <button disabled class="w-full py-3 px-4 rounded-xl font-medium text-sm transition-all bg-paleBlush text-forest cursor-not-allowed">
          Claimed! 🎉
        </button>
      `;
    } else {
      buttonHtml = `
        <button onclick="openClaimModal(${item.id})" class="w-full py-3 px-4 rounded-xl font-medium text-sm transition-all bg-plum hover:bg-plum-medium active:bg-plum-light text-white shadow-sm hover:shadow-md active:scale-[0.98]">
          Claim Gift
        </button>
      `;
    }
    
    card.innerHTML = `
      <!-- Product Image Container -->
      <div class="relative aspect-[4/3] w-full overflow-hidden bg-offWhite shrink-0 border-b border-paleBlush/10">
        <img src="${item.image}" alt="${item.title}" class="w-full h-full object-cover transition-transform duration-700 hover:scale-105 ${isClaimed ? 'opacity-40 filter grayscale-[30%]' : ''}" loading="lazy">
        ${isClaimed ? '<div class="absolute inset-0 bg-darkText/10 pointer-events-none"></div>' : ''}
      </div>
      
      <!-- Content Box -->
      <div class="p-6 flex flex-col flex-grow justify-between">
        <div class="mb-5">
          <h4 class="font-serif text-lg text-darkText font-semibold line-clamp-2 min-h-[3.25rem] flex items-center leading-snug mb-1">${item.title}</h4>
          <p class="text-plum font-semibold text-base">${formattedPrice}</p>
        </div>
        
        <div class="mt-auto">
          ${buttonHtml}
        </div>
      </div>
    `;
    
    grid.appendChild(card);
  });
}

// ==========================================
// 5. INTERACTIVE MODAL & CLAIMS WORKFLOW
// ==========================================
const claimModal = document.getElementById('claim-modal');
const successModal = document.getElementById('success-modal');
const claimForm = document.getElementById('claim-form');

const claimItemIdInput = document.getElementById('claim-item-id');
const claimItemTitleText = document.getElementById('claim-item-title');
const claimItemPriceText = document.getElementById('claim-item-price');

let activeClaimItemId = null;

function openClaimModal(itemId) {
  const item = registryItems.find(i => i.id === itemId);
  if (!item || item.claimed) return;
  
  activeClaimItemId = itemId;
  claimItemIdInput.value = itemId;
  claimItemTitleText.innerText = item.title;
  
  const formattedPrice = new Intl.NumberFormat('he-IL', { style: 'currency', currency: 'ILS', maximumFractionDigits: 0 }).format(item.price);
  claimItemPriceText.innerText = formattedPrice;
  
  // Show Modal with smooth animation
  claimModal.classList.add('modal-open');
  document.body.classList.add('overflow-hidden');
  
  // Focus name field
  setTimeout(() => {
    document.getElementById('claim-name').focus();
  }, 100);
}

function closeClaimModal() {
  claimModal.classList.remove('modal-open');
  document.body.classList.remove('overflow-hidden');
  claimForm.reset();
  activeClaimItemId = null;
}

// Handle Form Submission -> Set claimed true -> DB update -> Open Success
async function handleClaimSubmit(event) {
  event.preventDefault();
  
  const itemId = parseInt(claimItemIdInput.value, 10);
  const name = document.getElementById('claim-name').value.trim();
  const email = document.getElementById('claim-email').value.trim();
  
  if (!itemId || !name || !email) return;
  
  // 1. Toggle claimed property inside local array immediately
  const item = registryItems.find(i => i.id === itemId);
  if (item) {
    item.claimed = true;
  }
  
  // 2. Close Form Modal
  claimModal.classList.remove('modal-open');
  
  // 3. Open Success Modal Overlay
  successModal.classList.add('modal-open');
  
  // 4. Sync to DB asynchronously
  syncClaimToBackend(itemId, name, email);
}

// Persistence synchronization logic
async function syncClaimToBackend(itemId, name, email) {
  if (dbProvider === 'supabase' && supabaseClient) {
    try {
      const { error } = await supabaseClient
        .from(DATABASE_CONFIG.supabase.table)
        .upsert({ 
          item_id: itemId, 
          claimed: true, 
          claimer_name: name, 
          claimer_email: email 
        }, { onConflict: 'item_id' });
        
      if (error) throw error;
      console.log(`Successfully synced claim for item ${itemId} to Supabase`);
    } catch (e) {
      console.error("Failed to sync claim to Supabase, writing to localStorage fallback:", e);
      writeToLocalStorage(itemId, name, email);
    }
  } else if (dbProvider === 'firebase' && firestoreDb) {
    try {
      await firestoreDb.collection('registry_claims').doc(String(itemId)).set({
        claimed: true,
        claimer_name: name,
        claimer_email: email,
        claimed_at: firebase.firestore.FieldValue.serverTimestamp()
      });
      console.log(`Successfully synced claim for item ${itemId} to Firebase`);
    } catch (e) {
      console.error("Failed to sync claim to Firebase, writing to localStorage fallback:", e);
      writeToLocalStorage(itemId, name, email);
    }
  } else {
    // Fallback or explicit local storage choice
    writeToLocalStorage(itemId, name, email);
    console.log(`Saved claim for item ${itemId} locally.`);
  }
}

function writeToLocalStorage(itemId, name, email) {
  let claims = {};
  const savedClaims = localStorage.getItem('registry_claims');
  if (savedClaims) {
    try { claims = JSON.parse(savedClaims); } catch(e) {}
  }
  claims[itemId] = { 
    claimed: true, 
    name, 
    email, 
    claimed_at: new Date().toISOString() 
  };
  localStorage.setItem('registry_claims', JSON.stringify(claims));
  // Dispatch custom storage event for sync in local tab
  window.dispatchEvent(new Event('storage'));
}

function closeSuccessModal() {
  successModal.classList.remove('modal-open');
  document.body.classList.remove('overflow-hidden');
  
  // Refreshes the product grid instantly
  renderGrid();
}

// Expose functions globally to HTML handlers
window.openClaimModal = openClaimModal;
window.closeClaimModal = closeClaimModal;
window.closeSuccessModal = closeSuccessModal;

// Initialize on DOM Load
document.addEventListener('DOMContentLoaded', () => {
  initDatabase();
  
  // Event listeners
  document.getElementById('close-claim-modal').addEventListener('click', closeClaimModal);
  document.getElementById('cancel-claim-modal').addEventListener('click', closeClaimModal);
  document.getElementById('claim-form').addEventListener('submit', handleClaimSubmit);
  
  document.getElementById('place-order-btn').addEventListener('click', closeSuccessModal);
  
  // Close modals when clicking outside the container
  claimModal.addEventListener('click', (e) => {
    if (e.target === claimModal) closeClaimModal();
  });
  successModal.addEventListener('click', (e) => {
    if (e.target === successModal) closeSuccessModal();
  });
});
